In [1]:
import cv2

# Read image
img = cv2.imread('butterfly.jpg')

# Print pixel values
print(img)

[[[ 86  86  72]
  [ 86  86  72]
  [ 86  86  72]
  ...
  [112 109 104]
  [112 109 104]
  [112 109 104]]

 [[ 85  85  71]
  [ 85  85  71]
  [ 85  85  71]
  ...
  [112 109 104]
  [112 109 105]
  [112 109 105]]

 [[ 86  86  72]
  [ 86  86  72]
  [ 86  86  72]
  ...
  [112 109 105]
  [112 109 105]
  [112 109 105]]

 ...

 [[ 38  37  33]
  [ 36  35  31]
  [ 37  36  32]
  ...
  [ 29  30  26]
  [ 26  30  25]
  [ 26  30  25]]

 [[ 34  33  29]
  [ 35  32  28]
  [ 37  34  30]
  ...
  [ 29  30  26]
  [ 26  30  25]
  [ 26  30  25]]

 [[ 34  32  31]
  [ 34  32  31]
  [ 34  32  31]
  ...
  [ 28  29  25]
  [ 27  28  24]
  [ 27  28  24]]]


In [3]:
# import cv2

# img = cv2.imread('butterfly.jpg')

# Pixel at row 100, column 200
print(img[100, 200])

[98 96 90]


In [2]:
import cv2
import pandas as pd

# Read image
img = cv2.imread('butterfly.jpg')

# Check image loaded
if img is None:
    print("Image not found")
else:
    

    # Convert image pixels into rows
    pixels = img.reshape(-1, 3)

    # Create DataFrame with BGR values
    df = pd.DataFrame(
        pixels,
        columns=['Blue', 'Green', 'Red']
    )

    # Save to Excel
    df.to_excel(
        'pixel_values.xlsx',
        index=False
    )

    print("Pixel values saved to Excel")

Pixel values saved to Excel
